/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  JwtTokenDto,
} from '../models/index';
import {
    JwtTokenDtoFromJSON,
    JwtTokenDtoToJSON,
} from '../models/index';

export interface RefreshRequest {
    rEFRESHTOKEN?: string;
}

/**
 * 
 */
export class AuthControllerApi extends runtime.BaseAPI {

    /**
     * 액세스 토큰 만료 시 호출하여 새로운 액세스 토큰 및 리프레시 토큰을 발급받습니다.
     */
    async refreshRaw(requestParameters: RefreshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JwtTokenDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/auth/refresh`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JwtTokenDtoFromJSON(jsonValue));
    }

    /**
     * 액세스 토큰 만료 시 호출하여 새로운 액세스 토큰 및 리프레시 토큰을 발급받습니다.
     */
    async refresh(requestParameters: RefreshRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JwtTokenDto> {
        const response = await this.refreshRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
