/* tslint:disable */
/* eslint-disable */
/**
 * PlanList API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InferenceResultRequestDto,
  TrainingRequestDto,
  TrainingResultRequestDto,
} from '../models/index';
import {
    InferenceResultRequestDtoFromJSON,
    InferenceResultRequestDtoToJSON,
    TrainingRequestDtoFromJSON,
    TrainingRequestDtoToJSON,
    TrainingResultRequestDtoFromJSON,
    TrainingResultRequestDtoToJSON,
} from '../models/index';

export interface RequestInferenceRequest {
    projectId: number;
}

export interface RequestTrainingRequest {
    projectId: number;
    trainingRequestDto: TrainingRequestDto;
}

export interface ResponseInferenceRequest {
    projectId: number;
    inferenceResultRequestDto: InferenceResultRequestDto;
}

export interface ResponseTrainingRequest {
    projectId: number;
    trainingResultRequestDto: TrainingResultRequestDto;
}

/**
 * 
 */
export class ModelServerAPIApi extends runtime.BaseAPI {

    /**
     * 프론트에서 프로젝트 ID만 넘기면, 백엔드가 추론 요청을 보냅니다.
     * 모델 추론 요청
     */
    async requestInferenceRaw(requestParameters: RequestInferenceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling requestInference().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/model-server/projects/{projectId}/inference`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 프론트에서 프로젝트 ID만 넘기면, 백엔드가 추론 요청을 보냅니다.
     * 모델 추론 요청
     */
    async requestInference(requestParameters: RequestInferenceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.requestInferenceRaw(requestParameters, initOverrides);
    }

    /**
     * 클라이언트가 모델 서버에 학습을 요청합니다.
     * 모델 학습 요청
     */
    async requestTrainingRaw(requestParameters: RequestTrainingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling requestTraining().'
            );
        }

        if (requestParameters['trainingRequestDto'] == null) {
            throw new runtime.RequiredError(
                'trainingRequestDto',
                'Required parameter "trainingRequestDto" was null or undefined when calling requestTraining().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/model-server/training/{projectId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TrainingRequestDtoToJSON(requestParameters['trainingRequestDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 클라이언트가 모델 서버에 학습을 요청합니다.
     * 모델 학습 요청
     */
    async requestTraining(requestParameters: RequestTrainingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.requestTrainingRaw(requestParameters, initOverrides);
    }

    /**
     * 모델 서버가 추론 결과를 서버에 전달합니다.
     * 모델 추론 결과 수신
     */
    async responseInferenceRaw(requestParameters: ResponseInferenceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling responseInference().'
            );
        }

        if (requestParameters['inferenceResultRequestDto'] == null) {
            throw new runtime.RequiredError(
                'inferenceResultRequestDto',
                'Required parameter "inferenceResultRequestDto" was null or undefined when calling responseInference().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/model-server/projects/{projectId}/inference/result`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InferenceResultRequestDtoToJSON(requestParameters['inferenceResultRequestDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 모델 서버가 추론 결과를 서버에 전달합니다.
     * 모델 추론 결과 수신
     */
    async responseInference(requestParameters: ResponseInferenceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.responseInferenceRaw(requestParameters, initOverrides);
    }

    /**
     * 모델 서버가 학습 결과를 서버에 전달합니다.
     * 모델 학습 결과 수신
     */
    async responseTrainingRaw(requestParameters: ResponseTrainingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling responseTraining().'
            );
        }

        if (requestParameters['trainingResultRequestDto'] == null) {
            throw new runtime.RequiredError(
                'trainingResultRequestDto',
                'Required parameter "trainingResultRequestDto" was null or undefined when calling responseTraining().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/model-server/projects/{projectId}/training/result`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TrainingResultRequestDtoToJSON(requestParameters['trainingResultRequestDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 모델 서버가 학습 결과를 서버에 전달합니다.
     * 모델 학습 결과 수신
     */
    async responseTraining(requestParameters: ResponseTrainingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.responseTrainingRaw(requestParameters, initOverrides);
    }

}
