/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  UploadRoisRequest,
} from '../models/index';
import {
    UploadRoisRequestFromJSON,
    UploadRoisRequestToJSON,
} from '../models/index';

export interface UploadRoisOperationRequest {
    uploadRoisRequest?: UploadRoisRequest;
}

/**
 * 
 */
export class RoiControllerApi extends runtime.BaseAPI {

    /**
     */
    async uploadRoisRaw(requestParameters: UploadRoisOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/rois`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UploadRoisRequestToJSON(requestParameters['uploadRoisRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async uploadRois(requestParameters: UploadRoisOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.uploadRoisRaw(requestParameters, initOverrides);
    }

}
