/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnnotationHistorySummaryDto
 */
export interface AnnotationHistorySummaryDto {
    /**
     * 
     * @type {number}
     * @memberof AnnotationHistorySummaryDto
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof AnnotationHistorySummaryDto
     */
    order?: number;
    /**
     * 
     * @type {Date}
     * @memberof AnnotationHistorySummaryDto
     */
    startedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AnnotationHistorySummaryDto
     */
    completedAt?: Date;
}

/**
 * Check if a given object implements the AnnotationHistorySummaryDto interface.
 */
export function instanceOfAnnotationHistorySummaryDto(value: object): value is AnnotationHistorySummaryDto {
    return true;
}

export function AnnotationHistorySummaryDtoFromJSON(json: any): AnnotationHistorySummaryDto {
    return AnnotationHistorySummaryDtoFromJSONTyped(json, false);
}

export function AnnotationHistorySummaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnotationHistorySummaryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'order': json['order'] == null ? undefined : json['order'],
        'startedAt': json['startedAt'] == null ? undefined : (new Date(json['startedAt'])),
        'completedAt': json['completedAt'] == null ? undefined : (new Date(json['completedAt'])),
    };
}

export function AnnotationHistorySummaryDtoToJSON(json: any): AnnotationHistorySummaryDto {
    return AnnotationHistorySummaryDtoToJSONTyped(json, false);
}

export function AnnotationHistorySummaryDtoToJSONTyped(value?: AnnotationHistorySummaryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'order': value['order'],
        'startedAt': value['startedAt'] == null ? undefined : ((value['startedAt']).toISOString()),
        'completedAt': value['completedAt'] == null ? undefined : ((value['completedAt']).toISOString()),
    };
}

