/* tslint:disable */
/* eslint-disable */
/**
 * PlanList API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 베스트 공유 프로젝트 정보 DTO
 * @export
 * @interface BestProjectDto
 */
export interface BestProjectDto {
    /**
     * 공유 프로젝트 ID
     * @type {number}
     * @memberof BestProjectDto
     */
    sharedProjectId?: number;
    /**
     * 공유 프로젝트 제목
     * @type {string}
     * @memberof BestProjectDto
     */
    title?: string;
    /**
     * 작성자 이름
     * @type {string}
     * @memberof BestProjectDto
     */
    authorName?: string;
    /**
     * 프로필 이미지 URL
     * @type {string}
     * @memberof BestProjectDto
     */
    profileImageUrl?: string;
    /**
     * 다운로드 횟수
     * @type {number}
     * @memberof BestProjectDto
     */
    downloadCount?: number;
}

/**
 * Check if a given object implements the BestProjectDto interface.
 */
export function instanceOfBestProjectDto(value: object): value is BestProjectDto {
    return true;
}

export function BestProjectDtoFromJSON(json: any): BestProjectDto {
    return BestProjectDtoFromJSONTyped(json, false);
}

export function BestProjectDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BestProjectDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sharedProjectId': json['sharedProjectId'] == null ? undefined : json['sharedProjectId'],
        'title': json['title'] == null ? undefined : json['title'],
        'authorName': json['authorName'] == null ? undefined : json['authorName'],
        'profileImageUrl': json['profileImageUrl'] == null ? undefined : json['profileImageUrl'],
        'downloadCount': json['downloadCount'] == null ? undefined : json['downloadCount'],
    };
}

export function BestProjectDtoToJSON(json: any): BestProjectDto {
    return BestProjectDtoToJSONTyped(json, false);
}

export function BestProjectDtoToJSONTyped(value?: BestProjectDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sharedProjectId': value['sharedProjectId'],
        'title': value['title'],
        'authorName': value['authorName'],
        'profileImageUrl': value['profileImageUrl'],
        'downloadCount': value['downloadCount'],
    };
}

