/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PolygonDto } from './PolygonDto';
import {
    PolygonDtoFromJSON,
    PolygonDtoFromJSONTyped,
    PolygonDtoToJSON,
    PolygonDtoToJSONTyped,
} from './PolygonDto';

/**
 * 셀 정보
 * @export
 * @interface Cell
 */
export interface Cell {
    /**
     * 클래스 인덱스
     * @type {number}
     * @memberof Cell
     */
    classIndex?: number;
    /**
     * 
     * @type {PolygonDto}
     * @memberof Cell
     */
    polygon?: PolygonDto;
}

/**
 * Check if a given object implements the Cell interface.
 */
export function instanceOfCell(value: object): value is Cell {
    return true;
}

export function CellFromJSON(json: any): Cell {
    return CellFromJSONTyped(json, false);
}

export function CellFromJSONTyped(json: any, ignoreDiscriminator: boolean): Cell {
    if (json == null) {
        return json;
    }
    return {
        
        'classIndex': json['classIndex'] == null ? undefined : json['classIndex'],
        'polygon': json['polygon'] == null ? undefined : PolygonDtoFromJSON(json['polygon']),
    };
}

export function CellToJSON(json: any): Cell {
    return CellToJSONTyped(json, false);
}

export function CellToJSONTyped(value?: Cell | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'classIndex': value['classIndex'],
        'polygon': PolygonDtoToJSON(value['polygon']),
    };
}

