/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PointDto } from './PointDto';
import {
    PointDtoFromJSON,
    PointDtoFromJSONTyped,
    PointDtoToJSON,
    PointDtoToJSONTyped,
} from './PointDto';

/**
 * CellAnnotation 정보 리스트
 * @export
 * @interface CellDto
 */
export interface CellDto {
    /**
     * 사용한 라벨의 아이디
     * @type {number}
     * @memberof CellDto
     */
    labelId?: number;
    /**
     * 폴리곤 좌표 리스트
     * @type {Array<PointDto>}
     * @memberof CellDto
     */
    polygon?: Array<PointDto>;
}

/**
 * Check if a given object implements the CellDto interface.
 */
export function instanceOfCellDto(value: object): value is CellDto {
    return true;
}

export function CellDtoFromJSON(json: any): CellDto {
    return CellDtoFromJSONTyped(json, false);
}

export function CellDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CellDto {
    if (json == null) {
        return json;
    }
    return {
        
        'labelId': json['labelId'] == null ? undefined : json['labelId'],
        'polygon': json['polygon'] == null ? undefined : ((json['polygon'] as Array<any>).map(PointDtoFromJSON)),
    };
}

export function CellDtoToJSON(json: any): CellDto {
    return CellDtoToJSONTyped(json, false);
}

export function CellDtoToJSONTyped(value?: CellDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'labelId': value['labelId'],
        'polygon': value['polygon'] == null ? undefined : ((value['polygon'] as Array<any>).map(PointDtoToJSON)),
    };
}

