/* tslint:disable */
/* eslint-disable */
/**
 * PlanList API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PolygonDto } from './PolygonDto';
import {
    PolygonDtoFromJSON,
    PolygonDtoFromJSONTyped,
    PolygonDtoToJSON,
    PolygonDtoToJSONTyped,
} from './PolygonDto';

/**
 * 세포 어노테이션 정보
 * @export
 * @interface CellDetail
 */
export interface CellDetail {
    /**
     * 세포 클래스 인덱스
     * @type {number}
     * @memberof CellDetail
     */
    classIndex?: number;
    /**
     * 세포 색상 (Hex)
     * @type {string}
     * @memberof CellDetail
     */
    color?: string;
    /**
     * 
     * @type {PolygonDto}
     * @memberof CellDetail
     */
    polygon?: PolygonDto;
}

/**
 * Check if a given object implements the CellDetail interface.
 */
export function instanceOfCellDetail(value: object): value is CellDetail {
    return true;
}

export function CellDetailFromJSON(json: any): CellDetail {
    return CellDetailFromJSONTyped(json, false);
}

export function CellDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): CellDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'classIndex': json['classIndex'] == null ? undefined : json['classIndex'],
        'color': json['color'] == null ? undefined : json['color'],
        'polygon': json['polygon'] == null ? undefined : PolygonDtoFromJSON(json['polygon']),
    };
}

export function CellDetailToJSON(json: any): CellDetail {
    return CellDetailToJSONTyped(json, false);
}

export function CellDetailToJSONTyped(value?: CellDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'classIndex': value['classIndex'],
        'color': value['color'],
        'polygon': PolygonDtoToJSON(value['polygon']),
    };
}

