/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 세포 좌표 리스트
 * @export
 * @interface CellDetail
 */
export interface CellDetail {
    /**
     * 세포의 X 좌표
     * @type {number}
     * @memberof CellDetail
     */
    x?: number;
    /**
     * 세포의 Y 좌표
     * @type {number}
     * @memberof CellDetail
     */
    y?: number;
}

/**
 * Check if a given object implements the CellDetail interface.
 */
export function instanceOfCellDetail(value: object): value is CellDetail {
    return true;
}

export function CellDetailFromJSON(json: any): CellDetail {
    return CellDetailFromJSONTyped(json, false);
}

export function CellDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): CellDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'x': json['x'] == null ? undefined : json['x'],
        'y': json['y'] == null ? undefined : json['y'],
    };
}

export function CellDetailToJSON(json: any): CellDetail {
    return CellDetailToJSONTyped(json, false);
}

export function CellDetailToJSONTyped(value?: CellDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'x': value['x'],
        'y': value['y'],
    };
}

