/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProjectRequestDto
 */
export interface CreateProjectRequestDto {
    /**
     * 
     * @type {string}
     * @memberof CreateProjectRequestDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProjectRequestDto
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateProjectRequestDto
     */
    modelId?: number;
}

/**
 * Check if a given object implements the CreateProjectRequestDto interface.
 */
export function instanceOfCreateProjectRequestDto(value: object): value is CreateProjectRequestDto {
    return true;
}

export function CreateProjectRequestDtoFromJSON(json: any): CreateProjectRequestDto {
    return CreateProjectRequestDtoFromJSONTyped(json, false);
}

export function CreateProjectRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProjectRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'modelId': json['modelId'] == null ? undefined : json['modelId'],
    };
}

export function CreateProjectRequestDtoToJSON(json: any): CreateProjectRequestDto {
    return CreateProjectRequestDtoToJSONTyped(json, false);
}

export function CreateProjectRequestDtoToJSONTyped(value?: CreateProjectRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'modelId': value['modelId'],
    };
}

