/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSharedProjectDto
 */
export interface CreateSharedProjectDto {
    /**
     * 
     * @type {number}
     * @memberof CreateSharedProjectDto
     */
    projectId?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateSharedProjectDto
     */
    modelId?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateSharedProjectDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSharedProjectDto
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateSharedProjectDto
     */
    tags?: Array<string>;
}

/**
 * Check if a given object implements the CreateSharedProjectDto interface.
 */
export function instanceOfCreateSharedProjectDto(value: object): value is CreateSharedProjectDto {
    return true;
}

export function CreateSharedProjectDtoFromJSON(json: any): CreateSharedProjectDto {
    return CreateSharedProjectDtoFromJSONTyped(json, false);
}

export function CreateSharedProjectDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSharedProjectDto {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'modelId': json['modelId'] == null ? undefined : json['modelId'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function CreateSharedProjectDtoToJSON(json: any): CreateSharedProjectDto {
    return CreateSharedProjectDtoToJSONTyped(json, false);
}

export function CreateSharedProjectDtoToJSONTyped(value?: CreateSharedProjectDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'projectId': value['projectId'],
        'modelId': value['modelId'],
        'title': value['title'],
        'description': value['description'],
        'tags': value['tags'],
    };
}

