/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetNotificationsResponseDto
 */
export interface GetNotificationsResponseDto {
    /**
     * 알림 ID
     * @type {number}
     * @memberof GetNotificationsResponseDto
     */
    id?: number;
    /**
     * 알림 제목
     * @type {string}
     * @memberof GetNotificationsResponseDto
     */
    title?: string;
    /**
     * 알림 메시지 내용
     * @type {string}
     * @memberof GetNotificationsResponseDto
     */
    message?: string;
    /**
     * 클릭 시 이동할 경로
     * @type {string}
     * @memberof GetNotificationsResponseDto
     */
    redirectPath?: string;
    /**
     * 읽음 여부
     * @type {boolean}
     * @memberof GetNotificationsResponseDto
     */
    isRead?: boolean;
    /**
     * 알림 발생 후 경과 시간
     * @type {string}
     * @memberof GetNotificationsResponseDto
     */
    timeAgo?: string;
}

/**
 * Check if a given object implements the GetNotificationsResponseDto interface.
 */
export function instanceOfGetNotificationsResponseDto(value: object): value is GetNotificationsResponseDto {
    return true;
}

export function GetNotificationsResponseDtoFromJSON(json: any): GetNotificationsResponseDto {
    return GetNotificationsResponseDtoFromJSONTyped(json, false);
}

export function GetNotificationsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNotificationsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'message': json['message'] == null ? undefined : json['message'],
        'redirectPath': json['redirectPath'] == null ? undefined : json['redirectPath'],
        'isRead': json['isRead'] == null ? undefined : json['isRead'],
        'timeAgo': json['timeAgo'] == null ? undefined : json['timeAgo'],
    };
}

export function GetNotificationsResponseDtoToJSON(json: any): GetNotificationsResponseDto {
    return GetNotificationsResponseDtoToJSONTyped(json, false);
}

export function GetNotificationsResponseDtoToJSONTyped(value?: GetNotificationsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'message': value['message'],
        'redirectPath': value['redirectPath'],
        'isRead': value['isRead'],
        'timeAgo': value['timeAgo'],
    };
}

