/* tslint:disable */
/* eslint-disable */
/**
 * PlanList API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectModelsDto } from './ProjectModelsDto';
import {
    ProjectModelsDtoFromJSON,
    ProjectModelsDtoFromJSONTyped,
    ProjectModelsDtoToJSON,
    ProjectModelsDtoToJSONTyped,
} from './ProjectModelsDto';

/**
 * 프로젝트와 해당 프로젝트에 속한 모델 목록 응답 DTO
 * @export
 * @interface GetProjectWithModelsResponseDto
 */
export interface GetProjectWithModelsResponseDto {
    /**
     * 프로젝트 목록
     * @type {Array<ProjectModelsDto>}
     * @memberof GetProjectWithModelsResponseDto
     */
    projects?: Array<ProjectModelsDto>;
}

/**
 * Check if a given object implements the GetProjectWithModelsResponseDto interface.
 */
export function instanceOfGetProjectWithModelsResponseDto(value: object): value is GetProjectWithModelsResponseDto {
    return true;
}

export function GetProjectWithModelsResponseDtoFromJSON(json: any): GetProjectWithModelsResponseDto {
    return GetProjectWithModelsResponseDtoFromJSONTyped(json, false);
}

export function GetProjectWithModelsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProjectWithModelsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'projects': json['projects'] == null ? undefined : ((json['projects'] as Array<any>).map(ProjectModelsDtoFromJSON)),
    };
}

export function GetProjectWithModelsResponseDtoToJSON(json: any): GetProjectWithModelsResponseDto {
    return GetProjectWithModelsResponseDtoToJSONTyped(json, false);
}

export function GetProjectWithModelsResponseDtoToJSONTyped(value?: GetProjectWithModelsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'projects': value['projects'] == null ? undefined : ((value['projects'] as Array<any>).map(ProjectModelsDtoToJSON)),
    };
}

