/* tslint:disable */
/* eslint-disable */
/**
 * PlanList API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetProjectsResponseModelsDto } from './GetProjectsResponseModelsDto';
import {
    GetProjectsResponseModelsDtoFromJSON,
    GetProjectsResponseModelsDtoFromJSONTyped,
    GetProjectsResponseModelsDtoToJSON,
    GetProjectsResponseModelsDtoToJSONTyped,
} from './GetProjectsResponseModelsDto';
import type { PaginationResponseGetProjectsResponseDetailDto } from './PaginationResponseGetProjectsResponseDetailDto';
import {
    PaginationResponseGetProjectsResponseDetailDtoFromJSON,
    PaginationResponseGetProjectsResponseDetailDtoFromJSONTyped,
    PaginationResponseGetProjectsResponseDetailDtoToJSON,
    PaginationResponseGetProjectsResponseDetailDtoToJSONTyped,
} from './PaginationResponseGetProjectsResponseDetailDto';

/**
 * 
 * @export
 * @interface GetProjectsResponseDto
 */
export interface GetProjectsResponseDto {
    /**
     * 
     * @type {PaginationResponseGetProjectsResponseDetailDto}
     * @memberof GetProjectsResponseDto
     */
    project?: PaginationResponseGetProjectsResponseDetailDto;
    /**
     * 
     * @type {Array<GetProjectsResponseModelsDto>}
     * @memberof GetProjectsResponseDto
     */
    models?: Array<GetProjectsResponseModelsDto>;
}

/**
 * Check if a given object implements the GetProjectsResponseDto interface.
 */
export function instanceOfGetProjectsResponseDto(value: object): value is GetProjectsResponseDto {
    return true;
}

export function GetProjectsResponseDtoFromJSON(json: any): GetProjectsResponseDto {
    return GetProjectsResponseDtoFromJSONTyped(json, false);
}

export function GetProjectsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProjectsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'project': json['project'] == null ? undefined : PaginationResponseGetProjectsResponseDetailDtoFromJSON(json['project']),
        'models': json['models'] == null ? undefined : ((json['models'] as Array<any>).map(GetProjectsResponseModelsDtoFromJSON)),
    };
}

export function GetProjectsResponseDtoToJSON(json: any): GetProjectsResponseDto {
    return GetProjectsResponseDtoToJSONTyped(json, false);
}

export function GetProjectsResponseDtoToJSONTyped(value?: GetProjectsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project': PaginationResponseGetProjectsResponseDetailDtoToJSON(value['project']),
        'models': value['models'] == null ? undefined : ((value['models'] as Array<any>).map(GetProjectsResponseModelsDtoToJSON)),
    };
}

