/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetProjectsResponseModelsDto
 */
export interface GetProjectsResponseModelsDto {
    /**
     * 모델 id
     * @type {number}
     * @memberof GetProjectsResponseModelsDto
     */
    modelId?: number;
    /**
     * 모델 타입
     * @type {string}
     * @memberof GetProjectsResponseModelsDto
     */
    modelType?: GetProjectsResponseModelsDtoModelTypeEnum;
    /**
     * 모델명
     * @type {string}
     * @memberof GetProjectsResponseModelsDto
     */
    modelName?: string;
}


/**
 * @export
 */
export const GetProjectsResponseModelsDtoModelTypeEnum = {
    Tissue: 'TISSUE',
    Cell: 'CELL',
    Multi: 'MULTI'
} as const;
export type GetProjectsResponseModelsDtoModelTypeEnum = typeof GetProjectsResponseModelsDtoModelTypeEnum[keyof typeof GetProjectsResponseModelsDtoModelTypeEnum];


/**
 * Check if a given object implements the GetProjectsResponseModelsDto interface.
 */
export function instanceOfGetProjectsResponseModelsDto(value: object): value is GetProjectsResponseModelsDto {
    return true;
}

export function GetProjectsResponseModelsDtoFromJSON(json: any): GetProjectsResponseModelsDto {
    return GetProjectsResponseModelsDtoFromJSONTyped(json, false);
}

export function GetProjectsResponseModelsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProjectsResponseModelsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'modelId': json['modelId'] == null ? undefined : json['modelId'],
        'modelType': json['modelType'] == null ? undefined : json['modelType'],
        'modelName': json['modelName'] == null ? undefined : json['modelName'],
    };
}

export function GetProjectsResponseModelsDtoToJSON(json: any): GetProjectsResponseModelsDto {
    return GetProjectsResponseModelsDtoToJSONTyped(json, false);
}

export function GetProjectsResponseModelsDtoToJSONTyped(value?: GetProjectsResponseModelsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'modelId': value['modelId'],
        'modelType': value['modelType'],
        'modelName': value['modelName'],
    };
}

