/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetProjectsResponseDetailDto
 */
export interface GetProjectsResponseDetailDto {
    /**
     * 프로젝트 id
     * @type {number}
     * @memberof GetProjectsResponseDetailDto
     */
    projectId?: number;
    /**
     * 프로젝트명
     * @type {string}
     * @memberof GetProjectsResponseDetailDto
     */
    title?: string;
    /**
     * 프로젝트 생성일
     * @type {string}
     * @memberof GetProjectsResponseDetailDto
     */
    createdAt?: string;
    /**
     * 프로젝트 수정일
     * @type {string}
     * @memberof GetProjectsResponseDetailDto
     */
    updatedAt?: string;
    /**
     * 모델 타입
     * @type {string}
     * @memberof GetProjectsResponseDetailDto
     */
    modelType?: GetProjectsResponseDetailDtoModelTypeEnum;
    /**
     * 모델명
     * @type {string}
     * @memberof GetProjectsResponseDetailDto
     */
    modelName?: string;
    /**
     * 썸네일 이미지 url
     * @type {Array<string>}
     * @memberof GetProjectsResponseDetailDto
     */
    thumbnailUrl?: Array<string>;
}


/**
 * @export
 */
export const GetProjectsResponseDetailDtoModelTypeEnum = {
    Tissue: 'TISSUE',
    Cell: 'CELL',
    Multi: 'MULTI'
} as const;
export type GetProjectsResponseDetailDtoModelTypeEnum = typeof GetProjectsResponseDetailDtoModelTypeEnum[keyof typeof GetProjectsResponseDetailDtoModelTypeEnum];


/**
 * Check if a given object implements the GetProjectsResponseDetailDto interface.
 */
export function instanceOfGetProjectsResponseDetailDto(value: object): value is GetProjectsResponseDetailDto {
    return true;
}

export function GetProjectsResponseDetailDtoFromJSON(json: any): GetProjectsResponseDetailDto {
    return GetProjectsResponseDetailDtoFromJSONTyped(json, false);
}

export function GetProjectsResponseDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProjectsResponseDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'title': json['title'] == null ? undefined : json['title'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'modelType': json['modelType'] == null ? undefined : json['modelType'],
        'modelName': json['modelName'] == null ? undefined : json['modelName'],
        'thumbnailUrl': json['thumbnailUrl'] == null ? undefined : json['thumbnailUrl'],
    };
}

export function GetProjectsResponseDetailDtoToJSON(json: any): GetProjectsResponseDetailDto {
    return GetProjectsResponseDetailDtoToJSONTyped(json, false);
}

export function GetProjectsResponseDetailDtoToJSONTyped(value?: GetProjectsResponseDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'projectId': value['projectId'],
        'title': value['title'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'modelType': value['modelType'],
        'modelName': value['modelName'],
        'thumbnailUrl': value['thumbnailUrl'],
    };
}

