/* tslint:disable */
/* eslint-disable */
/**
 * PlanList API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationResponseGetSharedProjectsResponseDetailDto } from './PaginationResponseGetSharedProjectsResponseDetailDto';
import {
    PaginationResponseGetSharedProjectsResponseDetailDtoFromJSON,
    PaginationResponseGetSharedProjectsResponseDetailDtoFromJSONTyped,
    PaginationResponseGetSharedProjectsResponseDetailDtoToJSON,
    PaginationResponseGetSharedProjectsResponseDetailDtoToJSONTyped,
} from './PaginationResponseGetSharedProjectsResponseDetailDto';
import type { BestProjectDto } from './BestProjectDto';
import {
    BestProjectDtoFromJSON,
    BestProjectDtoFromJSONTyped,
    BestProjectDtoToJSON,
    BestProjectDtoToJSONTyped,
} from './BestProjectDto';

/**
 * 공유 프로젝트 리스트 및 베스트 프로젝트 응답 DTO
 * @export
 * @interface GetSharedProjectsResponseDto
 */
export interface GetSharedProjectsResponseDto {
    /**
     * 
     * @type {PaginationResponseGetSharedProjectsResponseDetailDto}
     * @memberof GetSharedProjectsResponseDto
     */
    sharedProject?: PaginationResponseGetSharedProjectsResponseDetailDto;
    /**
     * 베스트 공유 프로젝트 목록
     * @type {Array<BestProjectDto>}
     * @memberof GetSharedProjectsResponseDto
     */
    bestProjects?: Array<BestProjectDto>;
}

/**
 * Check if a given object implements the GetSharedProjectsResponseDto interface.
 */
export function instanceOfGetSharedProjectsResponseDto(value: object): value is GetSharedProjectsResponseDto {
    return true;
}

export function GetSharedProjectsResponseDtoFromJSON(json: any): GetSharedProjectsResponseDto {
    return GetSharedProjectsResponseDtoFromJSONTyped(json, false);
}

export function GetSharedProjectsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSharedProjectsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sharedProject': json['sharedProject'] == null ? undefined : PaginationResponseGetSharedProjectsResponseDetailDtoFromJSON(json['sharedProject']),
        'bestProjects': json['bestProjects'] == null ? undefined : ((json['bestProjects'] as Array<any>).map(BestProjectDtoFromJSON)),
    };
}

export function GetSharedProjectsResponseDtoToJSON(json: any): GetSharedProjectsResponseDto {
    return GetSharedProjectsResponseDtoToJSONTyped(json, false);
}

export function GetSharedProjectsResponseDtoToJSONTyped(value?: GetSharedProjectsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sharedProject': PaginationResponseGetSharedProjectsResponseDetailDtoToJSON(value['sharedProject']),
        'bestProjects': value['bestProjects'] == null ? undefined : ((value['bestProjects'] as Array<any>).map(BestProjectDtoToJSON)),
    };
}

