/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommentDto } from './CommentDto';
import {
    CommentDtoFromJSON,
    CommentDtoFromJSONTyped,
    CommentDtoToJSON,
    CommentDtoToJSONTyped,
} from './CommentDto';

/**
 * 공유 프로젝트의 댓글 목록 응답
 * @export
 * @interface GetSharedProjectCommentsResponseDto
 */
export interface GetSharedProjectCommentsResponseDto {
    /**
     * 댓글 리스트
     * @type {Array<CommentDto>}
     * @memberof GetSharedProjectCommentsResponseDto
     */
    comments?: Array<CommentDto>;
}

/**
 * Check if a given object implements the GetSharedProjectCommentsResponseDto interface.
 */
export function instanceOfGetSharedProjectCommentsResponseDto(value: object): value is GetSharedProjectCommentsResponseDto {
    return true;
}

export function GetSharedProjectCommentsResponseDtoFromJSON(json: any): GetSharedProjectCommentsResponseDto {
    return GetSharedProjectCommentsResponseDtoFromJSONTyped(json, false);
}

export function GetSharedProjectCommentsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSharedProjectCommentsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'comments': json['comments'] == null ? undefined : ((json['comments'] as Array<any>).map(CommentDtoFromJSON)),
    };
}

export function GetSharedProjectCommentsResponseDtoToJSON(json: any): GetSharedProjectCommentsResponseDto {
    return GetSharedProjectCommentsResponseDtoToJSONTyped(json, false);
}

export function GetSharedProjectCommentsResponseDtoToJSONTyped(value?: GetSharedProjectCommentsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comments': value['comments'] == null ? undefined : ((value['comments'] as Array<any>).map(CommentDtoToJSON)),
    };
}

