/* tslint:disable */
/* eslint-disable */
/**
 * PlanList API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelInfo } from './ModelInfo';
import {
    ModelInfoFromJSON,
    ModelInfoFromJSONTyped,
    ModelInfoToJSON,
    ModelInfoToJSONTyped,
} from './ModelInfo';

/**
 * 공유 프로젝트 상세 응답 DTO
 * @export
 * @interface GetSharedProjectDetailResponseDto
 */
export interface GetSharedProjectDetailResponseDto {
    /**
     * 공유 프로젝트 ID
     * @type {number}
     * @memberof GetSharedProjectDetailResponseDto
     */
    sharedProjectId?: number;
    /**
     * 공유 프로젝트 제목
     * @type {string}
     * @memberof GetSharedProjectDetailResponseDto
     */
    title?: string;
    /**
     * 공유 프로젝트 설명
     * @type {string}
     * @memberof GetSharedProjectDetailResponseDto
     */
    description?: string;
    /**
     * 공유 프로젝트 생성일
     * @type {Date}
     * @memberof GetSharedProjectDetailResponseDto
     */
    createdAt?: Date;
    /**
     * 작성자 이름
     * @type {string}
     * @memberof GetSharedProjectDetailResponseDto
     */
    authorName?: string;
    /**
     * 
     * @type {ModelInfo}
     * @memberof GetSharedProjectDetailResponseDto
     */
    model?: ModelInfo;
    /**
     * 태그 목록
     * @type {Array<string>}
     * @memberof GetSharedProjectDetailResponseDto
     */
    tags?: Array<string>;
    /**
     * 원본 이미지 경로 목록
     * @type {Array<string>}
     * @memberof GetSharedProjectDetailResponseDto
     */
    originalImagePaths?: Array<string>;
    /**
     * 결과 이미지 경로 목록
     * @type {Array<string>}
     * @memberof GetSharedProjectDetailResponseDto
     */
    resultImagePaths?: Array<string>;
}

/**
 * Check if a given object implements the GetSharedProjectDetailResponseDto interface.
 */
export function instanceOfGetSharedProjectDetailResponseDto(value: object): value is GetSharedProjectDetailResponseDto {
    return true;
}

export function GetSharedProjectDetailResponseDtoFromJSON(json: any): GetSharedProjectDetailResponseDto {
    return GetSharedProjectDetailResponseDtoFromJSONTyped(json, false);
}

export function GetSharedProjectDetailResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSharedProjectDetailResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sharedProjectId': json['sharedProjectId'] == null ? undefined : json['sharedProjectId'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'authorName': json['authorName'] == null ? undefined : json['authorName'],
        'model': json['model'] == null ? undefined : ModelInfoFromJSON(json['model']),
        'tags': json['tags'] == null ? undefined : json['tags'],
        'originalImagePaths': json['originalImagePaths'] == null ? undefined : json['originalImagePaths'],
        'resultImagePaths': json['resultImagePaths'] == null ? undefined : json['resultImagePaths'],
    };
}

export function GetSharedProjectDetailResponseDtoToJSON(json: any): GetSharedProjectDetailResponseDto {
    return GetSharedProjectDetailResponseDtoToJSONTyped(json, false);
}

export function GetSharedProjectDetailResponseDtoToJSONTyped(value?: GetSharedProjectDetailResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sharedProjectId': value['sharedProjectId'],
        'title': value['title'],
        'description': value['description'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'authorName': value['authorName'],
        'model': ModelInfoToJSON(value['model']),
        'tags': value['tags'],
        'originalImagePaths': value['originalImagePaths'],
        'resultImagePaths': value['resultImagePaths'],
    };
}

