/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 공유 프로젝트 상세 정보 DTO
 * @export
 * @interface GetSharedProjectsResponseDetailDto
 */
export interface GetSharedProjectsResponseDetailDto {
    /**
     * 공유 프로젝트 ID
     * @type {number}
     * @memberof GetSharedProjectsResponseDetailDto
     */
    sharedProjectId?: number;
    /**
     * 공유 프로젝트 제목
     * @type {string}
     * @memberof GetSharedProjectsResponseDetailDto
     */
    title?: string;
    /**
     * 작성자 이름
     * @type {string}
     * @memberof GetSharedProjectsResponseDetailDto
     */
    authorName?: string;
    /**
     * 썸네일 이미지 URL
     * @type {string}
     * @memberof GetSharedProjectsResponseDetailDto
     */
    thumbnailUrl?: string;
    /**
     * 태그 목록
     * @type {Array<string>}
     * @memberof GetSharedProjectsResponseDetailDto
     */
    tags?: Array<string>;
    /**
     * 다운로드 횟수
     * @type {number}
     * @memberof GetSharedProjectsResponseDetailDto
     */
    downloadCount?: number;
}

/**
 * Check if a given object implements the GetSharedProjectsResponseDetailDto interface.
 */
export function instanceOfGetSharedProjectsResponseDetailDto(value: object): value is GetSharedProjectsResponseDetailDto {
    return true;
}

export function GetSharedProjectsResponseDetailDtoFromJSON(json: any): GetSharedProjectsResponseDetailDto {
    return GetSharedProjectsResponseDetailDtoFromJSONTyped(json, false);
}

export function GetSharedProjectsResponseDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSharedProjectsResponseDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sharedProjectId': json['sharedProjectId'] == null ? undefined : json['sharedProjectId'],
        'title': json['title'] == null ? undefined : json['title'],
        'authorName': json['authorName'] == null ? undefined : json['authorName'],
        'thumbnailUrl': json['thumbnailUrl'] == null ? undefined : json['thumbnailUrl'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'downloadCount': json['downloadCount'] == null ? undefined : json['downloadCount'],
    };
}

export function GetSharedProjectsResponseDetailDtoToJSON(json: any): GetSharedProjectsResponseDetailDto {
    return GetSharedProjectsResponseDetailDtoToJSONTyped(json, false);
}

export function GetSharedProjectsResponseDetailDtoToJSONTyped(value?: GetSharedProjectsResponseDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sharedProjectId': value['sharedProjectId'],
        'title': value['title'],
        'authorName': value['authorName'],
        'thumbnailUrl': value['thumbnailUrl'],
        'tags': value['tags'],
        'downloadCount': value['downloadCount'],
    };
}

