/* tslint:disable */
/* eslint-disable */
/**
 * PlanList API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetUserSettingsResponseNotificationDto } from './GetUserSettingsResponseNotificationDto';
import {
    GetUserSettingsResponseNotificationDtoFromJSON,
    GetUserSettingsResponseNotificationDtoFromJSONTyped,
    GetUserSettingsResponseNotificationDtoToJSON,
    GetUserSettingsResponseNotificationDtoToJSONTyped,
} from './GetUserSettingsResponseNotificationDto';

/**
 * 
 * @export
 * @interface GetUserSettingsResponseDto
 */
export interface GetUserSettingsResponseDto {
    /**
     * 사용자 이메일
     * @type {string}
     * @memberof GetUserSettingsResponseDto
     */
    email?: string;
    /**
     * 사용자 이름
     * @type {string}
     * @memberof GetUserSettingsResponseDto
     */
    name?: string;
    /**
     * 프로필 이미지 경로
     * @type {string}
     * @memberof GetUserSettingsResponseDto
     */
    profileImagePath?: string;
    /**
     * 
     * @type {Array<GetUserSettingsResponseNotificationDto>}
     * @memberof GetUserSettingsResponseDto
     */
    notificationSettings?: Array<GetUserSettingsResponseNotificationDto>;
}

/**
 * Check if a given object implements the GetUserSettingsResponseDto interface.
 */
export function instanceOfGetUserSettingsResponseDto(value: object): value is GetUserSettingsResponseDto {
    return true;
}

export function GetUserSettingsResponseDtoFromJSON(json: any): GetUserSettingsResponseDto {
    return GetUserSettingsResponseDtoFromJSONTyped(json, false);
}

export function GetUserSettingsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserSettingsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'profileImagePath': json['profileImagePath'] == null ? undefined : json['profileImagePath'],
        'notificationSettings': json['notificationSettings'] == null ? undefined : ((json['notificationSettings'] as Array<any>).map(GetUserSettingsResponseNotificationDtoFromJSON)),
    };
}

export function GetUserSettingsResponseDtoToJSON(json: any): GetUserSettingsResponseDto {
    return GetUserSettingsResponseDtoToJSONTyped(json, false);
}

export function GetUserSettingsResponseDtoToJSONTyped(value?: GetUserSettingsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'name': value['name'],
        'profileImagePath': value['profileImagePath'],
        'notificationSettings': value['notificationSettings'] == null ? undefined : ((value['notificationSettings'] as Array<any>).map(GetUserSettingsResponseNotificationDtoToJSON)),
    };
}

