/* tslint:disable */
/* eslint-disable */
/**
 * PlanList API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LabelInfo } from './LabelInfo';
import {
    LabelInfoFromJSON,
    LabelInfoFromJSONTyped,
    LabelInfoToJSON,
    LabelInfoToJSONTyped,
} from './LabelInfo';
import type { SubProjectInfo } from './SubProjectInfo';
import {
    SubProjectInfoFromJSON,
    SubProjectInfoFromJSONTyped,
    SubProjectInfoToJSON,
    SubProjectInfoToJSONTyped,
} from './SubProjectInfo';

/**
 * 
 * @export
 * @interface InferenceResultRequestDto
 */
export interface InferenceResultRequestDto {
    /**
     * 추론 기록 ID
     * @type {number}
     * @memberof InferenceResultRequestDto
     */
    inferenceHistoryId?: number;
    /**
     * 프로젝트 ID
     * @type {number}
     * @memberof InferenceResultRequestDto
     */
    projectId?: number;
    /**
     * 요청 타입
     * @type {string}
     * @memberof InferenceResultRequestDto
     */
    modelRequestType?: InferenceResultRequestDtoModelRequestTypeEnum;
    /**
     * 모델 종류
     * @type {string}
     * @memberof InferenceResultRequestDto
     */
    modelType?: InferenceResultRequestDtoModelTypeEnum;
    /**
     * 모델 이름
     * @type {string}
     * @memberof InferenceResultRequestDto
     */
    modelName?: string;
    /**
     * 조직 모델 경로
     * @type {string}
     * @memberof InferenceResultRequestDto
     */
    tissueModelPath?: string;
    /**
     * 세포 모델 경로
     * @type {string}
     * @memberof InferenceResultRequestDto
     */
    cellModelPath?: string;
    /**
     * 모델 라벨 정보 목록
     * @type {Array<LabelInfo>}
     * @memberof InferenceResultRequestDto
     */
    labels?: Array<LabelInfo>;
    /**
     * SubProject 정보 목록
     * @type {Array<SubProjectInfo>}
     * @memberof InferenceResultRequestDto
     */
    subProjects?: Array<SubProjectInfo>;
}


/**
 * @export
 */
export const InferenceResultRequestDtoModelRequestTypeEnum = {
    Inference: 'INFERENCE',
    TrainingInference: 'TRAINING_INFERENCE'
} as const;
export type InferenceResultRequestDtoModelRequestTypeEnum = typeof InferenceResultRequestDtoModelRequestTypeEnum[keyof typeof InferenceResultRequestDtoModelRequestTypeEnum];

/**
 * @export
 */
export const InferenceResultRequestDtoModelTypeEnum = {
    Tissue: 'TISSUE',
    Cell: 'CELL',
    Multi: 'MULTI'
} as const;
export type InferenceResultRequestDtoModelTypeEnum = typeof InferenceResultRequestDtoModelTypeEnum[keyof typeof InferenceResultRequestDtoModelTypeEnum];


/**
 * Check if a given object implements the InferenceResultRequestDto interface.
 */
export function instanceOfInferenceResultRequestDto(value: object): value is InferenceResultRequestDto {
    return true;
}

export function InferenceResultRequestDtoFromJSON(json: any): InferenceResultRequestDto {
    return InferenceResultRequestDtoFromJSONTyped(json, false);
}

export function InferenceResultRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InferenceResultRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'inferenceHistoryId': json['inferenceHistoryId'] == null ? undefined : json['inferenceHistoryId'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'modelRequestType': json['modelRequestType'] == null ? undefined : json['modelRequestType'],
        'modelType': json['modelType'] == null ? undefined : json['modelType'],
        'modelName': json['modelName'] == null ? undefined : json['modelName'],
        'tissueModelPath': json['tissueModelPath'] == null ? undefined : json['tissueModelPath'],
        'cellModelPath': json['cellModelPath'] == null ? undefined : json['cellModelPath'],
        'labels': json['labels'] == null ? undefined : ((json['labels'] as Array<any>).map(LabelInfoFromJSON)),
        'subProjects': json['subProjects'] == null ? undefined : ((json['subProjects'] as Array<any>).map(SubProjectInfoFromJSON)),
    };
}

export function InferenceResultRequestDtoToJSON(json: any): InferenceResultRequestDto {
    return InferenceResultRequestDtoToJSONTyped(json, false);
}

export function InferenceResultRequestDtoToJSONTyped(value?: InferenceResultRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'inferenceHistoryId': value['inferenceHistoryId'],
        'projectId': value['projectId'],
        'modelRequestType': value['modelRequestType'],
        'modelType': value['modelType'],
        'modelName': value['modelName'],
        'tissueModelPath': value['tissueModelPath'],
        'cellModelPath': value['cellModelPath'],
        'labels': value['labels'] == null ? undefined : ((value['labels'] as Array<any>).map(LabelInfoToJSON)),
        'subProjects': value['subProjects'] == null ? undefined : ((value['subProjects'] as Array<any>).map(SubProjectInfoToJSON)),
    };
}

