/* tslint:disable */
/* eslint-disable */
/**
 * PlanList API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 라벨 정보
 * @export
 * @interface LabelInfo
 */
export interface LabelInfo {
    /**
     * 클래스 인덱스
     * @type {number}
     * @memberof LabelInfo
     */
    classIndex?: number;
    /**
     * 클래스 이름
     * @type {string}
     * @memberof LabelInfo
     */
    name?: string;
    /**
     * RGB 색상
     * @type {Array<number>}
     * @memberof LabelInfo
     */
    color?: Array<number>;
}

/**
 * Check if a given object implements the LabelInfo interface.
 */
export function instanceOfLabelInfo(value: object): value is LabelInfo {
    return true;
}

export function LabelInfoFromJSON(json: any): LabelInfo {
    return LabelInfoFromJSONTyped(json, false);
}

export function LabelInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabelInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'classIndex': json['classIndex'] == null ? undefined : json['classIndex'],
        'name': json['name'] == null ? undefined : json['name'],
        'color': json['color'] == null ? undefined : json['color'],
    };
}

export function LabelInfoToJSON(json: any): LabelInfo {
    return LabelInfoToJSONTyped(json, false);
}

export function LabelInfoToJSONTyped(value?: LabelInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'classIndex': value['classIndex'],
        'name': value['name'],
        'color': value['color'],
    };
}

