/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 라벨 정보 리스트
 * @export
 * @interface LabelDto
 */
export interface LabelDto {
    /**
     * 라벨 ID. 생성 시 null, 수정 시 값 필요
     * @type {number}
     * @memberof LabelDto
     */
    id?: number;
    /**
     * 라벨 이름
     * @type {string}
     * @memberof LabelDto
     */
    name?: string;
    /**
     * 라벨 색상 (HEX 코드)
     * @type {string}
     * @memberof LabelDto
     */
    color?: string;
    /**
     * 정렬 순서
     * @type {number}
     * @memberof LabelDto
     */
    displayOrder?: number;
    /**
     * 생성 일자
     * @type {Date}
     * @memberof LabelDto
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the LabelDto interface.
 */
export function instanceOfLabelDto(value: object): value is LabelDto {
    return true;
}

export function LabelDtoFromJSON(json: any): LabelDto {
    return LabelDtoFromJSONTyped(json, false);
}

export function LabelDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabelDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'color': json['color'] == null ? undefined : json['color'],
        'displayOrder': json['displayOrder'] == null ? undefined : json['displayOrder'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function LabelDtoToJSON(json: any): LabelDto {
    return LabelDtoToJSONTyped(json, false);
}

export function LabelDtoToJSONTyped(value?: LabelDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'color': value['color'],
        'displayOrder': value['displayOrder'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

