/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LabelDto
 */
export interface LabelDto {
    /**
     * 
     * @type {number}
     * @memberof LabelDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof LabelDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof LabelDto
     */
    color?: string;
}

/**
 * Check if a given object implements the LabelDto interface.
 */
export function instanceOfLabelDto(value: object): value is LabelDto {
    return true;
}

export function LabelDtoFromJSON(json: any): LabelDto {
    return LabelDtoFromJSONTyped(json, false);
}

export function LabelDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabelDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'color': json['color'] == null ? undefined : json['color'],
    };
}

export function LabelDtoToJSON(json: any): LabelDto {
    return LabelDtoToJSONTyped(json, false);
}

export function LabelDtoToJSONTyped(value?: LabelDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'color': value['color'],
    };
}

