/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelSummaryDto
 */
export interface ModelSummaryDto {
    /**
     * 
     * @type {number}
     * @memberof ModelSummaryDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelSummaryDto
     */
    name?: string;
}

/**
 * Check if a given object implements the ModelSummaryDto interface.
 */
export function instanceOfModelSummaryDto(value: object): value is ModelSummaryDto {
    return true;
}

export function ModelSummaryDtoFromJSON(json: any): ModelSummaryDto {
    return ModelSummaryDtoFromJSONTyped(json, false);
}

export function ModelSummaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelSummaryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ModelSummaryDtoToJSON(json: any): ModelSummaryDto {
    return ModelSummaryDtoToJSONTyped(json, false);
}

export function ModelSummaryDtoToJSONTyped(value?: ModelSummaryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

