/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 모델 정보 DTO
 * @export
 * @interface ModelInfo
 */
export interface ModelInfo {
    /**
     * 모델 ID
     * @type {number}
     * @memberof ModelInfo
     */
    modelId?: number;
    /**
     * 모델명
     * @type {string}
     * @memberof ModelInfo
     */
    modelName?: string;
}

/**
 * Check if a given object implements the ModelInfo interface.
 */
export function instanceOfModelInfo(value: object): value is ModelInfo {
    return true;
}

export function ModelInfoFromJSON(json: any): ModelInfo {
    return ModelInfoFromJSONTyped(json, false);
}

export function ModelInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'modelId': json['modelId'] == null ? undefined : json['modelId'],
        'modelName': json['modelName'] == null ? undefined : json['modelName'],
    };
}

export function ModelInfoToJSON(json: any): ModelInfo {
    return ModelInfoToJSONTyped(json, false);
}

export function ModelInfoToJSONTyped(value?: ModelInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'modelId': value['modelId'],
        'modelName': value['modelName'],
    };
}

