/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 모델 정보 DTO
 * @export
 * @interface ModelsDto
 */
export interface ModelsDto {
    /**
     * 모델 ID
     * @type {number}
     * @memberof ModelsDto
     */
    modelId?: number;
    /**
     * 모델명
     * @type {string}
     * @memberof ModelsDto
     */
    modelName?: string;
}

/**
 * Check if a given object implements the ModelsDto interface.
 */
export function instanceOfModelsDto(value: object): value is ModelsDto {
    return true;
}

export function ModelsDtoFromJSON(json: any): ModelsDto {
    return ModelsDtoFromJSONTyped(json, false);
}

export function ModelsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'modelId': json['modelId'] == null ? undefined : json['modelId'],
        'modelName': json['modelName'] == null ? undefined : json['modelName'],
    };
}

export function ModelsDtoToJSON(json: any): ModelsDto {
    return ModelsDtoToJSONTyped(json, false);
}

export function ModelsDtoToJSONTyped(value?: ModelsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'modelId': value['modelId'],
        'modelName': value['modelName'],
    };
}

