/* tslint:disable */
/* eslint-disable */
/**
 * PlanList API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelProcessDto
 */
export interface ModelProcessDto {
    /**
     * 학습 및 추론 상태
     * @type {string}
     * @memberof ModelProcessDto
     */
    status?: string;
    /**
     * 학습 및 추론 진행률
     * @type {number}
     * @memberof ModelProcessDto
     */
    progress?: number;
    /**
     * 현재 에폭
     * @type {number}
     * @memberof ModelProcessDto
     */
    currentEpoch?: number;
    /**
     * 총 에폭
     * @type {number}
     * @memberof ModelProcessDto
     */
    totalEpoch?: number;
    /**
     * 마지막 완료 시간
     * @type {string}
     * @memberof ModelProcessDto
     */
    estimatedCompletionDateTime?: string;
}

/**
 * Check if a given object implements the ModelProcessDto interface.
 */
export function instanceOfModelProcessDto(value: object): value is ModelProcessDto {
    return true;
}

export function ModelProcessDtoFromJSON(json: any): ModelProcessDto {
    return ModelProcessDtoFromJSONTyped(json, false);
}

export function ModelProcessDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelProcessDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'progress': json['progress'] == null ? undefined : json['progress'],
        'currentEpoch': json['currentEpoch'] == null ? undefined : json['currentEpoch'],
        'totalEpoch': json['totalEpoch'] == null ? undefined : json['totalEpoch'],
        'estimatedCompletionDateTime': json['estimatedCompletionDateTime'] == null ? undefined : json['estimatedCompletionDateTime'],
    };
}

export function ModelProcessDtoToJSON(json: any): ModelProcessDto {
    return ModelProcessDtoToJSONTyped(json, false);
}

export function ModelProcessDtoToJSONTyped(value?: ModelProcessDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'progress': value['progress'],
        'currentEpoch': value['currentEpoch'],
        'totalEpoch': value['totalEpoch'],
        'estimatedCompletionDateTime': value['estimatedCompletionDateTime'],
    };
}

