/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetProjectsResponseDetailDto } from './GetProjectsResponseDetailDto';
import {
    GetProjectsResponseDetailDtoFromJSON,
    GetProjectsResponseDetailDtoFromJSONTyped,
    GetProjectsResponseDetailDtoToJSON,
    GetProjectsResponseDetailDtoToJSONTyped,
} from './GetProjectsResponseDetailDto';

/**
 * 
 * @export
 * @interface PaginationResponseGetProjectsResponseDetailDto
 */
export interface PaginationResponseGetProjectsResponseDetailDto {
    /**
     * 
     * @type {Array<GetProjectsResponseDetailDto>}
     * @memberof PaginationResponseGetProjectsResponseDetailDto
     */
    content?: Array<GetProjectsResponseDetailDto>;
    /**
     * 한 페이지 컨텐츠 개수
     * @type {number}
     * @memberof PaginationResponseGetProjectsResponseDetailDto
     */
    pageSize?: number;
    /**
     * 현재 페이지 번호 (1부터 시작)
     * @type {number}
     * @memberof PaginationResponseGetProjectsResponseDetailDto
     */
    currentPage?: number;
    /**
     * 전체 페이지 수
     * @type {number}
     * @memberof PaginationResponseGetProjectsResponseDetailDto
     */
    totalPages?: number;
    /**
     * 전체 요소 수
     * @type {number}
     * @memberof PaginationResponseGetProjectsResponseDetailDto
     */
    totalElements?: number;
}

/**
 * Check if a given object implements the PaginationResponseGetProjectsResponseDetailDto interface.
 */
export function instanceOfPaginationResponseGetProjectsResponseDetailDto(value: object): value is PaginationResponseGetProjectsResponseDetailDto {
    return true;
}

export function PaginationResponseGetProjectsResponseDetailDtoFromJSON(json: any): PaginationResponseGetProjectsResponseDetailDto {
    return PaginationResponseGetProjectsResponseDetailDtoFromJSONTyped(json, false);
}

export function PaginationResponseGetProjectsResponseDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationResponseGetProjectsResponseDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(GetProjectsResponseDetailDtoFromJSON)),
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
    };
}

export function PaginationResponseGetProjectsResponseDetailDtoToJSON(json: any): PaginationResponseGetProjectsResponseDetailDto {
    return PaginationResponseGetProjectsResponseDetailDtoToJSONTyped(json, false);
}

export function PaginationResponseGetProjectsResponseDetailDtoToJSONTyped(value?: PaginationResponseGetProjectsResponseDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(GetProjectsResponseDetailDtoToJSON)),
        'pageSize': value['pageSize'],
        'currentPage': value['currentPage'],
        'totalPages': value['totalPages'],
        'totalElements': value['totalElements'],
    };
}

