/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetNotificationsResponseDto } from './GetNotificationsResponseDto';
import {
    GetNotificationsResponseDtoFromJSON,
    GetNotificationsResponseDtoFromJSONTyped,
    GetNotificationsResponseDtoToJSON,
    GetNotificationsResponseDtoToJSONTyped,
} from './GetNotificationsResponseDto';

/**
 * 
 * @export
 * @interface PaginationResponseGetNotificationsResponseDto
 */
export interface PaginationResponseGetNotificationsResponseDto {
    /**
     * 
     * @type {Array<GetNotificationsResponseDto>}
     * @memberof PaginationResponseGetNotificationsResponseDto
     */
    content?: Array<GetNotificationsResponseDto>;
    /**
     * 한 페이지 컨텐츠 개수
     * @type {number}
     * @memberof PaginationResponseGetNotificationsResponseDto
     */
    pageSize?: number;
    /**
     * 현재 페이지 번호 (1부터 시작)
     * @type {number}
     * @memberof PaginationResponseGetNotificationsResponseDto
     */
    currentPage?: number;
    /**
     * 전체 페이지 수
     * @type {number}
     * @memberof PaginationResponseGetNotificationsResponseDto
     */
    totalPages?: number;
    /**
     * 전체 요소 수
     * @type {number}
     * @memberof PaginationResponseGetNotificationsResponseDto
     */
    totalElements?: number;
}

/**
 * Check if a given object implements the PaginationResponseGetNotificationsResponseDto interface.
 */
export function instanceOfPaginationResponseGetNotificationsResponseDto(value: object): value is PaginationResponseGetNotificationsResponseDto {
    return true;
}

export function PaginationResponseGetNotificationsResponseDtoFromJSON(json: any): PaginationResponseGetNotificationsResponseDto {
    return PaginationResponseGetNotificationsResponseDtoFromJSONTyped(json, false);
}

export function PaginationResponseGetNotificationsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationResponseGetNotificationsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(GetNotificationsResponseDtoFromJSON)),
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
    };
}

export function PaginationResponseGetNotificationsResponseDtoToJSON(json: any): PaginationResponseGetNotificationsResponseDto {
    return PaginationResponseGetNotificationsResponseDtoToJSONTyped(json, false);
}

export function PaginationResponseGetNotificationsResponseDtoToJSONTyped(value?: PaginationResponseGetNotificationsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(GetNotificationsResponseDtoToJSON)),
        'pageSize': value['pageSize'],
        'currentPage': value['currentPage'],
        'totalPages': value['totalPages'],
        'totalElements': value['totalElements'],
    };
}

