/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetSharedProjectsResponseDetailDto } from './GetSharedProjectsResponseDetailDto';
import {
    GetSharedProjectsResponseDetailDtoFromJSON,
    GetSharedProjectsResponseDetailDtoFromJSONTyped,
    GetSharedProjectsResponseDetailDtoToJSON,
    GetSharedProjectsResponseDetailDtoToJSONTyped,
} from './GetSharedProjectsResponseDetailDto';

/**
 * 페이지네이션된 공유 프로젝트 목록
 * @export
 * @interface PaginationResponseGetSharedProjectsResponseDetailDto
 */
export interface PaginationResponseGetSharedProjectsResponseDetailDto {
    /**
     * 
     * @type {Array<GetSharedProjectsResponseDetailDto>}
     * @memberof PaginationResponseGetSharedProjectsResponseDetailDto
     */
    content?: Array<GetSharedProjectsResponseDetailDto>;
    /**
     * 한 페이지 컨텐츠 개수
     * @type {number}
     * @memberof PaginationResponseGetSharedProjectsResponseDetailDto
     */
    pageSize?: number;
    /**
     * 현재 페이지 번호 (1부터 시작)
     * @type {number}
     * @memberof PaginationResponseGetSharedProjectsResponseDetailDto
     */
    currentPage?: number;
    /**
     * 전체 페이지 수
     * @type {number}
     * @memberof PaginationResponseGetSharedProjectsResponseDetailDto
     */
    totalPages?: number;
    /**
     * 전체 요소 수
     * @type {number}
     * @memberof PaginationResponseGetSharedProjectsResponseDetailDto
     */
    totalElements?: number;
}

/**
 * Check if a given object implements the PaginationResponseGetSharedProjectsResponseDetailDto interface.
 */
export function instanceOfPaginationResponseGetSharedProjectsResponseDetailDto(value: object): value is PaginationResponseGetSharedProjectsResponseDetailDto {
    return true;
}

export function PaginationResponseGetSharedProjectsResponseDetailDtoFromJSON(json: any): PaginationResponseGetSharedProjectsResponseDetailDto {
    return PaginationResponseGetSharedProjectsResponseDetailDtoFromJSONTyped(json, false);
}

export function PaginationResponseGetSharedProjectsResponseDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationResponseGetSharedProjectsResponseDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(GetSharedProjectsResponseDetailDtoFromJSON)),
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
    };
}

export function PaginationResponseGetSharedProjectsResponseDetailDtoToJSON(json: any): PaginationResponseGetSharedProjectsResponseDetailDto {
    return PaginationResponseGetSharedProjectsResponseDetailDtoToJSONTyped(json, false);
}

export function PaginationResponseGetSharedProjectsResponseDetailDtoToJSONTyped(value?: PaginationResponseGetSharedProjectsResponseDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(GetSharedProjectsResponseDetailDtoToJSON)),
        'pageSize': value['pageSize'],
        'currentPage': value['currentPage'],
        'totalPages': value['totalPages'],
        'totalElements': value['totalElements'],
    };
}

