/* tslint:disable */
/* eslint-disable */
/**
 * PlanList API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 모델 성능 지표
 * @export
 * @interface Performance
 */
export interface Performance {
    /**
     * 정확도
     * @type {number}
     * @memberof Performance
     */
    accuracy?: number;
    /**
     * 손실값
     * @type {number}
     * @memberof Performance
     */
    loss?: number;
    /**
     * 반복 성능 점수
     * @type {number}
     * @memberof Performance
     */
    loopPerformance?: number;
}

/**
 * Check if a given object implements the Performance interface.
 */
export function instanceOfPerformance(value: object): value is Performance {
    return true;
}

export function PerformanceFromJSON(json: any): Performance {
    return PerformanceFromJSONTyped(json, false);
}

export function PerformanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Performance {
    if (json == null) {
        return json;
    }
    return {
        
        'accuracy': json['accuracy'] == null ? undefined : json['accuracy'],
        'loss': json['loss'] == null ? undefined : json['loss'],
        'loopPerformance': json['loopPerformance'] == null ? undefined : json['loopPerformance'],
    };
}

export function PerformanceToJSON(json: any): Performance {
    return PerformanceToJSONTyped(json, false);
}

export function PerformanceToJSONTyped(value?: Performance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accuracy': value['accuracy'],
        'loss': value['loss'],
        'loopPerformance': value['loopPerformance'],
    };
}

