/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 2D 평면의 좌표
 * @export
 * @interface PointDto
 */
export interface PointDto {
    /**
     * X 좌표
     * @type {number}
     * @memberof PointDto
     */
    x?: number;
    /**
     * Y 좌표
     * @type {number}
     * @memberof PointDto
     */
    y?: number;
}

/**
 * Check if a given object implements the PointDto interface.
 */
export function instanceOfPointDto(value: object): value is PointDto {
    return true;
}

export function PointDtoFromJSON(json: any): PointDto {
    return PointDtoFromJSONTyped(json, false);
}

export function PointDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PointDto {
    if (json == null) {
        return json;
    }
    return {
        
        'x': json['x'] == null ? undefined : json['x'],
        'y': json['y'] == null ? undefined : json['y'],
    };
}

export function PointDtoToJSON(json: any): PointDto {
    return PointDtoToJSONTyped(json, false);
}

export function PointDtoToJSONTyped(value?: PointDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'x': value['x'],
        'y': value['y'],
    };
}

