/* tslint:disable */
/* eslint-disable */
/**
 * PlanList API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PointDto } from './PointDto';
import {
    PointDtoFromJSON,
    PointDtoFromJSONTyped,
    PointDtoToJSON,
    PointDtoToJSONTyped,
} from './PointDto';

/**
 * Polygon 좌표 정보 DTO
 * @export
 * @interface PolygonDto
 */
export interface PolygonDto {
    /**
     * 꼭짓점 좌표 리스트
     * @type {Array<PointDto>}
     * @memberof PolygonDto
     */
    points?: Array<PointDto>;
}

/**
 * Check if a given object implements the PolygonDto interface.
 */
export function instanceOfPolygonDto(value: object): value is PolygonDto {
    return true;
}

export function PolygonDtoFromJSON(json: any): PolygonDto {
    return PolygonDtoFromJSONTyped(json, false);
}

export function PolygonDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolygonDto {
    if (json == null) {
        return json;
    }
    return {
        
        'points': json['points'] == null ? undefined : ((json['points'] as Array<any>).map(PointDtoFromJSON)),
    };
}

export function PolygonDtoToJSON(json: any): PolygonDto {
    return PolygonDtoToJSONTyped(json, false);
}

export function PolygonDtoToJSONTyped(value?: PolygonDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'points': value['points'] == null ? undefined : ((value['points'] as Array<any>).map(PointDtoToJSON)),
    };
}

