/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubProjectSummaryDto } from './SubProjectSummaryDto';
import {
    SubProjectSummaryDtoFromJSON,
    SubProjectSummaryDtoFromJSONTyped,
    SubProjectSummaryDtoToJSON,
    SubProjectSummaryDtoToJSONTyped,
} from './SubProjectSummaryDto';

/**
 * 
 * @export
 * @interface ProjectDetailDto
 */
export interface ProjectDetailDto {
    /**
     * 
     * @type {number}
     * @memberof ProjectDetailDto
     */
    projectId?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectDetailDto
     */
    title?: string;
    /**
     * 
     * @type {Array<SubProjectSummaryDto>}
     * @memberof ProjectDetailDto
     */
    subProjects?: Array<SubProjectSummaryDto>;
}

/**
 * Check if a given object implements the ProjectDetailDto interface.
 */
export function instanceOfProjectDetailDto(value: object): value is ProjectDetailDto {
    return true;
}

export function ProjectDetailDtoFromJSON(json: any): ProjectDetailDto {
    return ProjectDetailDtoFromJSONTyped(json, false);
}

export function ProjectDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'title': json['title'] == null ? undefined : json['title'],
        'subProjects': json['subProjects'] == null ? undefined : ((json['subProjects'] as Array<any>).map(SubProjectSummaryDtoFromJSON)),
    };
}

export function ProjectDetailDtoToJSON(json: any): ProjectDetailDto {
    return ProjectDetailDtoToJSONTyped(json, false);
}

export function ProjectDetailDtoToJSONTyped(value?: ProjectDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'projectId': value['projectId'],
        'title': value['title'],
        'subProjects': value['subProjects'] == null ? undefined : ((value['subProjects'] as Array<any>).map(SubProjectSummaryDtoToJSON)),
    };
}

