/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 프로젝트에서 사용되는 라벨 정보 DTO
 * @export
 * @interface ProjectLabelDto
 */
export interface ProjectLabelDto {
    /**
     * 라벨 ID
     * @type {number}
     * @memberof ProjectLabelDto
     */
    labelId?: number;
    /**
     * 라벨 이름
     * @type {string}
     * @memberof ProjectLabelDto
     */
    name?: string;
    /**
     * 라벨 색상 (HEX 코드)
     * @type {string}
     * @memberof ProjectLabelDto
     */
    color?: string;
    /**
     * 정렬 순서
     * @type {number}
     * @memberof ProjectLabelDto
     */
    displayOrder?: number;
    /**
     * 생성 일자
     * @type {Date}
     * @memberof ProjectLabelDto
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the ProjectLabelDto interface.
 */
export function instanceOfProjectLabelDto(value: object): value is ProjectLabelDto {
    return true;
}

export function ProjectLabelDtoFromJSON(json: any): ProjectLabelDto {
    return ProjectLabelDtoFromJSONTyped(json, false);
}

export function ProjectLabelDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectLabelDto {
    if (json == null) {
        return json;
    }
    return {
        
        'labelId': json['labelId'] == null ? undefined : json['labelId'],
        'name': json['name'] == null ? undefined : json['name'],
        'color': json['color'] == null ? undefined : json['color'],
        'displayOrder': json['displayOrder'] == null ? undefined : json['displayOrder'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function ProjectLabelDtoToJSON(json: any): ProjectLabelDto {
    return ProjectLabelDtoToJSONTyped(json, false);
}

export function ProjectLabelDtoToJSONTyped(value?: ProjectLabelDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'labelId': value['labelId'],
        'name': value['name'],
        'color': value['color'],
        'displayOrder': value['displayOrder'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

