/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 단일 모델 정보 DTO
 * @export
 * @interface ProjectModelsDto
 */
export interface ProjectModelsDto {
    /**
     * 모델 ID
     * @type {number}
     * @memberof ProjectModelsDto
     */
    modelId?: number;
    /**
     * 모델 이름
     * @type {string}
     * @memberof ProjectModelsDto
     */
    name?: string;
}

/**
 * Check if a given object implements the ProjectModelsDto interface.
 */
export function instanceOfProjectModelsDto(value: object): value is ProjectModelsDto {
    return true;
}

export function ProjectModelsDtoFromJSON(json: any): ProjectModelsDto {
    return ProjectModelsDtoFromJSONTyped(json, false);
}

export function ProjectModelsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectModelsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'modelId': json['modelId'] == null ? undefined : json['modelId'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ProjectModelsDtoToJSON(json: any): ProjectModelsDto {
    return ProjectModelsDtoToJSONTyped(json, false);
}

export function ProjectModelsDtoToJSONTyped(value?: ProjectModelsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'modelId': value['modelId'],
        'name': value['name'],
    };
}

