/* tslint:disable */
/* eslint-disable */
/**
 * PlanList API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ROI의 위치 정보
 * @export
 * @interface RoiDetail
 */
export interface RoiDetail {
    /**
     * X 좌표
     * @type {number}
     * @memberof RoiDetail
     */
    x?: number;
    /**
     * Y 좌표
     * @type {number}
     * @memberof RoiDetail
     */
    y?: number;
    /**
     * 너비
     * @type {number}
     * @memberof RoiDetail
     */
    width?: number;
    /**
     * 높이
     * @type {number}
     * @memberof RoiDetail
     */
    height?: number;
}

/**
 * Check if a given object implements the RoiDetail interface.
 */
export function instanceOfRoiDetail(value: object): value is RoiDetail {
    return true;
}

export function RoiDetailFromJSON(json: any): RoiDetail {
    return RoiDetailFromJSONTyped(json, false);
}

export function RoiDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoiDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'x': json['x'] == null ? undefined : json['x'],
        'y': json['y'] == null ? undefined : json['y'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
    };
}

export function RoiDetailToJSON(json: any): RoiDetail {
    return RoiDetailToJSONTyped(json, false);
}

export function RoiDetailToJSONTyped(value?: RoiDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'x': value['x'],
        'y': value['y'],
        'width': value['width'],
        'height': value['height'],
    };
}

