/* tslint:disable */
/* eslint-disable */
/**
 * PlanList API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoiSaveRequestDto } from './RoiSaveRequestDto';
import {
    RoiSaveRequestDtoFromJSON,
    RoiSaveRequestDtoFromJSONTyped,
    RoiSaveRequestDtoToJSON,
    RoiSaveRequestDtoToJSONTyped,
} from './RoiSaveRequestDto';
import type { LabelDto } from './LabelDto';
import {
    LabelDtoFromJSON,
    LabelDtoFromJSONTyped,
    LabelDtoToJSON,
    LabelDtoToJSONTyped,
} from './LabelDto';

/**
 * ROI, 라벨 정보 리스트
 * @export
 * @interface RoiLabelSaveRequestDto
 */
export interface RoiLabelSaveRequestDto {
    /**
     * ROI 정보 리스트
     * @type {Array<RoiSaveRequestDto>}
     * @memberof RoiLabelSaveRequestDto
     */
    rois?: Array<RoiSaveRequestDto>;
    /**
     * 라벨 정보 리스트
     * @type {Array<LabelDto>}
     * @memberof RoiLabelSaveRequestDto
     */
    labels?: Array<LabelDto>;
}

/**
 * Check if a given object implements the RoiLabelSaveRequestDto interface.
 */
export function instanceOfRoiLabelSaveRequestDto(value: object): value is RoiLabelSaveRequestDto {
    return true;
}

export function RoiLabelSaveRequestDtoFromJSON(json: any): RoiLabelSaveRequestDto {
    return RoiLabelSaveRequestDtoFromJSONTyped(json, false);
}

export function RoiLabelSaveRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoiLabelSaveRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'rois': json['rois'] == null ? undefined : ((json['rois'] as Array<any>).map(RoiSaveRequestDtoFromJSON)),
        'labels': json['labels'] == null ? undefined : ((json['labels'] as Array<any>).map(LabelDtoFromJSON)),
    };
}

export function RoiLabelSaveRequestDtoToJSON(json: any): RoiLabelSaveRequestDto {
    return RoiLabelSaveRequestDtoToJSONTyped(json, false);
}

export function RoiLabelSaveRequestDtoToJSONTyped(value?: RoiLabelSaveRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rois': value['rois'] == null ? undefined : ((value['rois'] as Array<any>).map(RoiSaveRequestDtoToJSON)),
        'labels': value['labels'] == null ? undefined : ((value['labels'] as Array<any>).map(LabelDtoToJSON)),
    };
}

