/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoiRequestDto
 */
export interface RoiRequestDto {
    /**
     * 
     * @type {number}
     * @memberof RoiRequestDto
     */
    x?: number;
    /**
     * 
     * @type {number}
     * @memberof RoiRequestDto
     */
    y?: number;
    /**
     * 
     * @type {number}
     * @memberof RoiRequestDto
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof RoiRequestDto
     */
    height?: number;
}

/**
 * Check if a given object implements the RoiRequestDto interface.
 */
export function instanceOfRoiRequestDto(value: object): value is RoiRequestDto {
    return true;
}

export function RoiRequestDtoFromJSON(json: any): RoiRequestDto {
    return RoiRequestDtoFromJSONTyped(json, false);
}

export function RoiRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoiRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'x': json['x'] == null ? undefined : json['x'],
        'y': json['y'] == null ? undefined : json['y'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
    };
}

export function RoiRequestDtoToJSON(json: any): RoiRequestDto {
    return RoiRequestDtoToJSONTyped(json, false);
}

export function RoiRequestDtoToJSONTyped(value?: RoiRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'x': value['x'],
        'y': value['y'],
        'width': value['width'],
        'height': value['height'],
    };
}

