/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CellDetail } from './CellDetail';
import {
    CellDetailFromJSON,
    CellDetailFromJSONTyped,
    CellDetailToJSON,
    CellDetailToJSONTyped,
} from './CellDetail';
import type { RoiResponseDto } from './RoiResponseDto';
import {
    RoiResponseDtoFromJSON,
    RoiResponseDtoFromJSONTyped,
    RoiResponseDtoToJSON,
    RoiResponseDtoToJSONTyped,
} from './RoiResponseDto';

/**
 * 
 * @export
 * @interface RoiResponsePayload
 */
export interface RoiResponsePayload {
    /**
     * 
     * @type {RoiResponseDto}
     * @memberof RoiResponsePayload
     */
    detail?: RoiResponseDto;
    /**
     * 
     * @type {Array<string>}
     * @memberof RoiResponsePayload
     */
    tissuePath?: Array<string>;
    /**
     * 
     * @type {Array<CellDetail>}
     * @memberof RoiResponsePayload
     */
    cell?: Array<CellDetail>;
}

/**
 * Check if a given object implements the RoiResponsePayload interface.
 */
export function instanceOfRoiResponsePayload(value: object): value is RoiResponsePayload {
    return true;
}

export function RoiResponsePayloadFromJSON(json: any): RoiResponsePayload {
    return RoiResponsePayloadFromJSONTyped(json, false);
}

export function RoiResponsePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoiResponsePayload {
    if (json == null) {
        return json;
    }
    return {
        
        'detail': json['detail'] == null ? undefined : RoiResponseDtoFromJSON(json['detail']),
        'tissuePath': json['tissue_path'] == null ? undefined : json['tissue_path'],
        'cell': json['cell'] == null ? undefined : ((json['cell'] as Array<any>).map(CellDetailFromJSON)),
    };
}

export function RoiResponsePayloadToJSON(json: any): RoiResponsePayload {
    return RoiResponsePayloadToJSONTyped(json, false);
}

export function RoiResponsePayloadToJSONTyped(value?: RoiResponsePayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detail': RoiResponseDtoToJSON(value['detail']),
        'tissue_path': value['tissuePath'],
        'cell': value['cell'] == null ? undefined : ((value['cell'] as Array<any>).map(CellDetailToJSON)),
    };
}

