/* tslint:disable */
/* eslint-disable */
/**
 * PlanList API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ROI의 위치 및 크기 정보
 * @export
 * @interface RoiResponseDto
 */
export interface RoiResponseDto {
    /**
     * ROI ID
     * @type {number}
     * @memberof RoiResponseDto
     */
    id?: number;
    /**
     * ROI의 X 좌표
     * @type {number}
     * @memberof RoiResponseDto
     */
    x?: number;
    /**
     * ROI의 Y 좌표
     * @type {number}
     * @memberof RoiResponseDto
     */
    y?: number;
    /**
     * ROI의 너비
     * @type {number}
     * @memberof RoiResponseDto
     */
    width?: number;
    /**
     * ROI의 높이
     * @type {number}
     * @memberof RoiResponseDto
     */
    height?: number;
    /**
     * ROI의 결함 백분율 19
     * @type {number}
     * @memberof RoiResponseDto
     */
    faulty?: number;
}

/**
 * Check if a given object implements the RoiResponseDto interface.
 */
export function instanceOfRoiResponseDto(value: object): value is RoiResponseDto {
    return true;
}

export function RoiResponseDtoFromJSON(json: any): RoiResponseDto {
    return RoiResponseDtoFromJSONTyped(json, false);
}

export function RoiResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoiResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'x': json['x'] == null ? undefined : json['x'],
        'y': json['y'] == null ? undefined : json['y'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
        'faulty': json['faulty'] == null ? undefined : json['faulty'],
    };
}

export function RoiResponseDtoToJSON(json: any): RoiResponseDto {
    return RoiResponseDtoToJSONTyped(json, false);
}

export function RoiResponseDtoToJSONTyped(value?: RoiResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'x': value['x'],
        'y': value['y'],
        'width': value['width'],
        'height': value['height'],
        'faulty': value['faulty'],
    };
}

