/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CellDto } from './CellDto';
import {
    CellDtoFromJSON,
    CellDtoFromJSONTyped,
    CellDtoToJSON,
    CellDtoToJSONTyped,
} from './CellDto';

/**
 * ROI 정보 리스트
 * @export
 * @interface RoiSaveRequestDto
 */
export interface RoiSaveRequestDto {
    /**
     * 
     * @type {number}
     * @memberof RoiSaveRequestDto
     */
    roiId?: number;
    /**
     * 
     * @type {number}
     * @memberof RoiSaveRequestDto
     */
    x?: number;
    /**
     * 
     * @type {number}
     * @memberof RoiSaveRequestDto
     */
    y?: number;
    /**
     * 
     * @type {number}
     * @memberof RoiSaveRequestDto
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof RoiSaveRequestDto
     */
    height?: number;
    /**
     * 
     * @type {number}
     * @memberof RoiSaveRequestDto
     */
    displayOrder?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof RoiSaveRequestDto
     */
    imageNames?: Array<string>;
    /**
     * CellAnnotation 정보 리스트
     * @type {Array<CellDto>}
     * @memberof RoiSaveRequestDto
     */
    cells?: Array<CellDto>;
}

/**
 * Check if a given object implements the RoiSaveRequestDto interface.
 */
export function instanceOfRoiSaveRequestDto(value: object): value is RoiSaveRequestDto {
    return true;
}

export function RoiSaveRequestDtoFromJSON(json: any): RoiSaveRequestDto {
    return RoiSaveRequestDtoFromJSONTyped(json, false);
}

export function RoiSaveRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoiSaveRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'roiId': json['roiId'] == null ? undefined : json['roiId'],
        'x': json['x'] == null ? undefined : json['x'],
        'y': json['y'] == null ? undefined : json['y'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
        'displayOrder': json['displayOrder'] == null ? undefined : json['displayOrder'],
        'imageNames': json['imageNames'] == null ? undefined : json['imageNames'],
        'cells': json['cells'] == null ? undefined : ((json['cells'] as Array<any>).map(CellDtoFromJSON)),
    };
}

export function RoiSaveRequestDtoToJSON(json: any): RoiSaveRequestDto {
    return RoiSaveRequestDtoToJSONTyped(json, false);
}

export function RoiSaveRequestDtoToJSONTyped(value?: RoiSaveRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'roiId': value['roiId'],
        'x': value['x'],
        'y': value['y'],
        'width': value['width'],
        'height': value['height'],
        'displayOrder': value['displayOrder'],
        'imageNames': value['imageNames'],
        'cells': value['cells'] == null ? undefined : ((value['cells'] as Array<any>).map(CellDtoToJSON)),
    };
}

