/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SlideSummaryDto
 */
export interface SlideSummaryDto {
    /**
     * 총 슬라이드 개수
     * @type {number}
     * @memberof SlideSummaryDto
     */
    totalSlides?: number;
    /**
     * 업로드 진행률
     * @type {number}
     * @memberof SlideSummaryDto
     */
    uploadProgress?: number;
    /**
     * 마지막 업로드 시간
     * @type {string}
     * @memberof SlideSummaryDto
     */
    lastUploadedDateTime?: string;
}

/**
 * Check if a given object implements the SlideSummaryDto interface.
 */
export function instanceOfSlideSummaryDto(value: object): value is SlideSummaryDto {
    return true;
}

export function SlideSummaryDtoFromJSON(json: any): SlideSummaryDto {
    return SlideSummaryDtoFromJSONTyped(json, false);
}

export function SlideSummaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SlideSummaryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalSlides': json['totalSlides'] == null ? undefined : json['totalSlides'],
        'uploadProgress': json['uploadProgress'] == null ? undefined : json['uploadProgress'],
        'lastUploadedDateTime': json['lastUploadedDateTime'] == null ? undefined : json['lastUploadedDateTime'],
    };
}

export function SlideSummaryDtoToJSON(json: any): SlideSummaryDto {
    return SlideSummaryDtoToJSONTyped(json, false);
}

export function SlideSummaryDtoToJSONTyped(value?: SlideSummaryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalSlides': value['totalSlides'],
        'uploadProgress': value['uploadProgress'],
        'lastUploadedDateTime': value['lastUploadedDateTime'],
    };
}

