/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SlideDto
 */
export interface SlideDto {
    /**
     * 서브 프로젝트 id
     * @type {number}
     * @memberof SlideDto
     */
    subProjectId?: number;
    /**
     * 썸네일 이미지 url
     * @type {string}
     * @memberof SlideDto
     */
    thumbnailUrl?: string;
    /**
     * 파일명
     * @type {string}
     * @memberof SlideDto
     */
    name?: string;
    /**
     * 파일 크기
     * @type {string}
     * @memberof SlideDto
     */
    size?: string;
    /**
     * 업로드 날짜
     * @type {string}
     * @memberof SlideDto
     */
    uploadedOn?: string;
}

/**
 * Check if a given object implements the SlideDto interface.
 */
export function instanceOfSlideDto(value: object): value is SlideDto {
    return true;
}

export function SlideDtoFromJSON(json: any): SlideDto {
    return SlideDtoFromJSONTyped(json, false);
}

export function SlideDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SlideDto {
    if (json == null) {
        return json;
    }
    return {
        
        'subProjectId': json['subProjectId'] == null ? undefined : json['subProjectId'],
        'thumbnailUrl': json['thumbnailUrl'] == null ? undefined : json['thumbnailUrl'],
        'name': json['name'] == null ? undefined : json['name'],
        'size': json['size'] == null ? undefined : json['size'],
        'uploadedOn': json['uploadedOn'] == null ? undefined : json['uploadedOn'],
    };
}

export function SlideDtoToJSON(json: any): SlideDto {
    return SlideDtoToJSONTyped(json, false);
}

export function SlideDtoToJSONTyped(value?: SlideDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subProjectId': value['subProjectId'],
        'thumbnailUrl': value['thumbnailUrl'],
        'name': value['name'],
        'size': value['size'],
        'uploadedOn': value['uploadedOn'],
    };
}

