/* tslint:disable */
/* eslint-disable */
/**
 * PlanList API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 서브 프로젝트 요약 정보 DTO
 * @export
 * @interface SubProjectSummaryDto
 */
export interface SubProjectSummaryDto {
    /**
     * 서브 프로젝트 ID
     * @type {number}
     * @memberof SubProjectSummaryDto
     */
    subProjectId?: number;
    /**
     * 서브 프로젝트 썸네일 URL
     * @type {string}
     * @memberof SubProjectSummaryDto
     */
    thumbnailUrl?: string;
    /**
     * 타일링 이미지 URL
     * @type {string}
     * @memberof SubProjectSummaryDto
     */
    tileImageUrl?: string;
    /**
     * 이미지 업로드 여부 완료
     * @type {boolean}
     * @memberof SubProjectSummaryDto
     */
    isUploadComplete?: boolean;
}

/**
 * Check if a given object implements the SubProjectSummaryDto interface.
 */
export function instanceOfSubProjectSummaryDto(value: object): value is SubProjectSummaryDto {
    return true;
}

export function SubProjectSummaryDtoFromJSON(json: any): SubProjectSummaryDto {
    return SubProjectSummaryDtoFromJSONTyped(json, false);
}

export function SubProjectSummaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubProjectSummaryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'subProjectId': json['subProjectId'] == null ? undefined : json['subProjectId'],
        'thumbnailUrl': json['thumbnailUrl'] == null ? undefined : json['thumbnailUrl'],
        'tileImageUrl': json['tileImageUrl'] == null ? undefined : json['tileImageUrl'],
        'isUploadComplete': json['isUploadComplete'] == null ? undefined : json['isUploadComplete'],
    };
}

export function SubProjectSummaryDtoToJSON(json: any): SubProjectSummaryDto {
    return SubProjectSummaryDtoToJSONTyped(json, false);
}

export function SubProjectSummaryDtoToJSONTyped(value?: SubProjectSummaryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subProjectId': value['subProjectId'],
        'thumbnailUrl': value['thumbnailUrl'],
        'tileImageUrl': value['tileImageUrl'],
        'isUploadComplete': value['isUploadComplete'],
    };
}

