/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrainingRequestDto
 */
export interface TrainingRequestDto {
    /**
     * 
     * @type {string}
     * @memberof TrainingRequestDto
     */
    modelName?: string;
}

/**
 * Check if a given object implements the TrainingRequestDto interface.
 */
export function instanceOfTrainingRequestDto(value: object): value is TrainingRequestDto {
    return true;
}

export function TrainingRequestDtoFromJSON(json: any): TrainingRequestDto {
    return TrainingRequestDtoFromJSONTyped(json, false);
}

export function TrainingRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrainingRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'modelName': json['modelName'] == null ? undefined : json['modelName'],
    };
}

export function TrainingRequestDtoToJSON(json: any): TrainingRequestDto {
    return TrainingRequestDtoToJSONTyped(json, false);
}

export function TrainingRequestDtoToJSONTyped(value?: TrainingRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'modelName': value['modelName'],
    };
}

