/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoiRequestPayload } from './RoiRequestPayload';
import {
    RoiRequestPayloadFromJSON,
    RoiRequestPayloadFromJSONTyped,
    RoiRequestPayloadToJSON,
    RoiRequestPayloadToJSONTyped,
} from './RoiRequestPayload';

/**
 * 모델 학습 결과 데이터
 * @export
 * @interface TrainingResultRequestDto
 */
export interface TrainingResultRequestDto {
    /**
     * 학습된 모델이 저장된 경로
     * @type {string}
     * @memberof TrainingResultRequestDto
     */
    modelPath: string;
    /**
     * 학습 결과 ROI 정보 리스트
     * @type {Array<RoiRequestPayload>}
     * @memberof TrainingResultRequestDto
     */
    roi: Array<RoiRequestPayload>;
}

/**
 * Check if a given object implements the TrainingResultRequestDto interface.
 */
export function instanceOfTrainingResultRequestDto(value: object): value is TrainingResultRequestDto {
    if (!('modelPath' in value) || value['modelPath'] === undefined) return false;
    if (!('roi' in value) || value['roi'] === undefined) return false;
    return true;
}

export function TrainingResultRequestDtoFromJSON(json: any): TrainingResultRequestDto {
    return TrainingResultRequestDtoFromJSONTyped(json, false);
}

export function TrainingResultRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrainingResultRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'modelPath': json['model_path'],
        'roi': ((json['roi'] as Array<any>).map(RoiRequestPayloadFromJSON)),
    };
}

export function TrainingResultRequestDtoToJSON(json: any): TrainingResultRequestDto {
    return TrainingResultRequestDtoToJSONTyped(json, false);
}

export function TrainingResultRequestDtoToJSONTyped(value?: TrainingResultRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model_path': value['modelPath'],
        'roi': ((value['roi'] as Array<any>).map(RoiRequestPayloadToJSON)),
    };
}

