/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoiRequestPayload } from './RoiRequestPayload';
import {
    RoiRequestPayloadFromJSON,
    RoiRequestPayloadFromJSONTyped,
    RoiRequestPayloadToJSON,
    RoiRequestPayloadToJSONTyped,
} from './RoiRequestPayload';

/**
 * 
 * @export
 * @interface TrainingResultRequestDto
 */
export interface TrainingResultRequestDto {
    /**
     * 
     * @type {number}
     * @memberof TrainingResultRequestDto
     */
    subProjectId?: number;
    /**
     * 
     * @type {number}
     * @memberof TrainingResultRequestDto
     */
    annotationHistoryId?: number;
    /**
     * 
     * @type {string}
     * @memberof TrainingResultRequestDto
     */
    modelPath?: string;
    /**
     * 
     * @type {Array<RoiRequestPayload>}
     * @memberof TrainingResultRequestDto
     */
    roi?: Array<RoiRequestPayload>;
}

/**
 * Check if a given object implements the TrainingResultRequestDto interface.
 */
export function instanceOfTrainingResultRequestDto(value: object): value is TrainingResultRequestDto {
    return true;
}

export function TrainingResultRequestDtoFromJSON(json: any): TrainingResultRequestDto {
    return TrainingResultRequestDtoFromJSONTyped(json, false);
}

export function TrainingResultRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrainingResultRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'subProjectId': json['sub_project_id'] == null ? undefined : json['sub_project_id'],
        'annotationHistoryId': json['annotation_history_id'] == null ? undefined : json['annotation_history_id'],
        'modelPath': json['model_path'] == null ? undefined : json['model_path'],
        'roi': json['roi'] == null ? undefined : ((json['roi'] as Array<any>).map(RoiRequestPayloadFromJSON)),
    };
}

export function TrainingResultRequestDtoToJSON(json: any): TrainingResultRequestDto {
    return TrainingResultRequestDtoToJSONTyped(json, false);
}

export function TrainingResultRequestDtoToJSONTyped(value?: TrainingResultRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sub_project_id': value['subProjectId'],
        'annotation_history_id': value['annotationHistoryId'],
        'model_path': value['modelPath'],
        'roi': value['roi'] == null ? undefined : ((value['roi'] as Array<any>).map(RoiRequestPayloadToJSON)),
    };
}

