/* tslint:disable */
/* eslint-disable */
/**
 * PlanList API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 댓글 수정 요청
 * @export
 * @interface UpdateCommentRequestDto
 */
export interface UpdateCommentRequestDto {
    /**
     * 수정할 댓글 내용
     * @type {string}
     * @memberof UpdateCommentRequestDto
     */
    content?: string;
}

/**
 * Check if a given object implements the UpdateCommentRequestDto interface.
 */
export function instanceOfUpdateCommentRequestDto(value: object): value is UpdateCommentRequestDto {
    return true;
}

export function UpdateCommentRequestDtoFromJSON(json: any): UpdateCommentRequestDto {
    return UpdateCommentRequestDtoFromJSONTyped(json, false);
}

export function UpdateCommentRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCommentRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function UpdateCommentRequestDtoToJSON(json: any): UpdateCommentRequestDto {
    return UpdateCommentRequestDtoToJSONTyped(json, false);
}

export function UpdateCommentRequestDtoToJSONTyped(value?: UpdateCommentRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

