/* tslint:disable */
/* eslint-disable */
/**
 * PlanList API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserNotificationSettingsRequestNotificationDto
 */
export interface UpdateUserNotificationSettingsRequestNotificationDto {
    /**
     * 알림 타입
     * @type {string}
     * @memberof UpdateUserNotificationSettingsRequestNotificationDto
     */
    type?: string;
    /**
     * 알림 활성화 여부
     * @type {boolean}
     * @memberof UpdateUserNotificationSettingsRequestNotificationDto
     */
    enabled?: boolean;
}

/**
 * Check if a given object implements the UpdateUserNotificationSettingsRequestNotificationDto interface.
 */
export function instanceOfUpdateUserNotificationSettingsRequestNotificationDto(value: object): value is UpdateUserNotificationSettingsRequestNotificationDto {
    return true;
}

export function UpdateUserNotificationSettingsRequestNotificationDtoFromJSON(json: any): UpdateUserNotificationSettingsRequestNotificationDto {
    return UpdateUserNotificationSettingsRequestNotificationDtoFromJSONTyped(json, false);
}

export function UpdateUserNotificationSettingsRequestNotificationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserNotificationSettingsRequestNotificationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
    };
}

export function UpdateUserNotificationSettingsRequestNotificationDtoToJSON(json: any): UpdateUserNotificationSettingsRequestNotificationDto {
    return UpdateUserNotificationSettingsRequestNotificationDtoToJSONTyped(json, false);
}

export function UpdateUserNotificationSettingsRequestNotificationDtoToJSONTyped(value?: UpdateUserNotificationSettingsRequestNotificationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'enabled': value['enabled'],
    };
}

