/* tslint:disable */
/* eslint-disable */
/**
 * PlanList API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserNameRequestDto
 */
export interface UpdateUserNameRequestDto {
    /**
     * 사용자 이름
     * @type {string}
     * @memberof UpdateUserNameRequestDto
     */
    name?: string;
}

/**
 * Check if a given object implements the UpdateUserNameRequestDto interface.
 */
export function instanceOfUpdateUserNameRequestDto(value: object): value is UpdateUserNameRequestDto {
    return true;
}

export function UpdateUserNameRequestDtoFromJSON(json: any): UpdateUserNameRequestDto {
    return UpdateUserNameRequestDtoFromJSONTyped(json, false);
}

export function UpdateUserNameRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserNameRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function UpdateUserNameRequestDtoToJSON(json: any): UpdateUserNameRequestDto {
    return UpdateUserNameRequestDtoToJSONTyped(json, false);
}

export function UpdateUserNameRequestDtoToJSONTyped(value?: UpdateUserNameRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

