/* tslint:disable */
/* eslint-disable */
/**
 * Pathos
 * Pathos의 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProjectRequestDto
 */
export interface UpdateProjectRequestDto {
    /**
     * 프로젝트명
     * @type {string}
     * @memberof UpdateProjectRequestDto
     */
    title?: string;
    /**
     * 프로젝트 설명
     * @type {string}
     * @memberof UpdateProjectRequestDto
     */
    description?: string;
}

/**
 * Check if a given object implements the UpdateProjectRequestDto interface.
 */
export function instanceOfUpdateProjectRequestDto(value: object): value is UpdateProjectRequestDto {
    return true;
}

export function UpdateProjectRequestDtoFromJSON(json: any): UpdateProjectRequestDto {
    return UpdateProjectRequestDtoFromJSONTyped(json, false);
}

export function UpdateProjectRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProjectRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function UpdateProjectRequestDtoToJSON(json: any): UpdateProjectRequestDto {
    return UpdateProjectRequestDtoToJSONTyped(json, false);
}

export function UpdateProjectRequestDtoToJSONTyped(value?: UpdateProjectRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
    };
}

