/* tslint:disable */
/* eslint-disable */
/**
 * PlanList API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateUserNotificationSettingsRequestNotificationDto } from './UpdateUserNotificationSettingsRequestNotificationDto';
import {
    UpdateUserNotificationSettingsRequestNotificationDtoFromJSON,
    UpdateUserNotificationSettingsRequestNotificationDtoFromJSONTyped,
    UpdateUserNotificationSettingsRequestNotificationDtoToJSON,
    UpdateUserNotificationSettingsRequestNotificationDtoToJSONTyped,
} from './UpdateUserNotificationSettingsRequestNotificationDto';

/**
 * 
 * @export
 * @interface UpdateNotificationSettingsRequestDto
 */
export interface UpdateNotificationSettingsRequestDto {
    /**
     * 
     * @type {Array<UpdateUserNotificationSettingsRequestNotificationDto>}
     * @memberof UpdateNotificationSettingsRequestDto
     */
    settings?: Array<UpdateUserNotificationSettingsRequestNotificationDto>;
}

/**
 * Check if a given object implements the UpdateNotificationSettingsRequestDto interface.
 */
export function instanceOfUpdateNotificationSettingsRequestDto(value: object): value is UpdateNotificationSettingsRequestDto {
    return true;
}

export function UpdateNotificationSettingsRequestDtoFromJSON(json: any): UpdateNotificationSettingsRequestDto {
    return UpdateNotificationSettingsRequestDtoFromJSONTyped(json, false);
}

export function UpdateNotificationSettingsRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateNotificationSettingsRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'settings': json['settings'] == null ? undefined : ((json['settings'] as Array<any>).map(UpdateUserNotificationSettingsRequestNotificationDtoFromJSON)),
    };
}

export function UpdateNotificationSettingsRequestDtoToJSON(json: any): UpdateNotificationSettingsRequestDto {
    return UpdateNotificationSettingsRequestDtoToJSONTyped(json, false);
}

export function UpdateNotificationSettingsRequestDtoToJSONTyped(value?: UpdateNotificationSettingsRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'settings': value['settings'] == null ? undefined : ((value['settings'] as Array<any>).map(UpdateUserNotificationSettingsRequestNotificationDtoToJSON)),
    };
}

